### GET ALL ITEMS
GET http://localhost:5000/items HTTP/1.1

### GET SINGLE ITEM
GET http://localhost:5000/items/1 HTTP/1.1

### ADD ITEM
POST http://localhost:5000/items HTTP/1.1
Content-Type: application/json

{
  "name": "itemBaru"
}

### DELETE ITEM
DELETE  http://localhost:5000/items/82e0113a-cf8d-4eb7-8c1e-1e1906a76b7c HTTP/1.1


### UPDATE ITEM
PUT http://localhost:5000/items/2 HTTP/1.1
Content-Type: application/json

{
  "name": "Kimoci Item"
}